# -*- coding: utf-8 -*-
# Deployment settings for c:\marmalade\7.31\quick\target\win\quick_prebuilt.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.31/s3e/makefile_builder/mkb.py', 'c:/Users/jgrossman/Documents/Work/Blog/FlappyJam/FlappyJam.mkb', '--buildenv=QUICK', '--use-prebuilt', '--debug', '--no-ide', '--execute', '--deploy-only']
mkb = 'c:/Users/jgrossman/Documents/Work/Blog/FlappyJam/FlappyJam.mkb'
mkf = ['c:\\marmalade\\7.31\\quick\\quick_prebuilt.mkf', 'c:\\marmalade\\7.31\\quick\\quick_prebuilt_options.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/jgrossman/Documents/Work/Blog/FlappyJam/resources', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'FlappyJam'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'FlappyJam'
    long_caption = 'FlappyJam'
    version = [0, 0, 1]
    config = ['c:/Users/jgrossman/Documents/Work/Blog/FlappyJam/resources/common.icf', 'c:/Users/jgrossman/Documents/Work/Blog/FlappyJam/resources/app.icf']
    data_dir = 'c:/Users/jgrossman/Documents/Work/Blog/FlappyJam/resources'
    iphone_link_lib = ['s3eFacebook', 's3eIOSAppStoreBilling', 's3eIOSGameCenter', 's3eWebView', 's3eFlurry', 'FlurryAnalytics']
    osx_ext_dll = ['c:/marmalade/7.31/extensions/s3eWebView/lib/osx/libs3eWebView.dylib']
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/marmalade/7.31/extensions/s3eWebView/lib/win32/s3eWebView.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = ['c:/marmalade/7.31/extensions/s3eFacebook/lib/iphone', 'c:/marmalade/7.31/extensions/s3eIOSAppStoreBilling/lib/iphone', 'c:/marmalade/7.31/extensions/s3eIOSGameCenter/lib/iphone', 'c:/marmalade/7.31/extensions/s3eWebView/lib/iphone', 'c:/marmalade/7.31/extensions/s3eFlurry/lib/iphone']
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws81_ext_sdk_ref_file = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = ['c:/marmalade/7.31/extensions/s3eFacebook/lib/android/s3eFacebook.jar', 'c:/marmalade/7.31/extensions/s3eAmazonInAppPurchasing/lib/android/s3eAmazonInAppPurchasing.jar', 'c:/marmalade/7.31/extensions/s3eAmazonInAppPurchasing/lib/android/in-app-purchasing-1.0.3.jar', 'c:/marmalade/7.31/extensions/s3eAndroidGooglePlayBilling/lib/android/s3eAndroidGooglePlayBilling.jar', 'c:/marmalade/7.31/extensions/s3eAndroidMarketBilling/lib/android/s3eAndroidMarketBilling.jar', 'c:/marmalade/7.31/extensions/s3eSamsungInAppPurchasing/lib/android/s3eSamsungInAppPurchasing.jar', 'c:/marmalade/7.31/extensions/s3eSamsungInAppPurchasing/lib/android/iap2.0_lib.jar', 'c:/marmalade/7.31/extensions/Fortumo/lib/android/Fortumo.jar', 'c:/marmalade/7.31/extensions/s3eFlurry/lib/android/s3eFlurry.jar', 'c:/marmalade/7.31/extensions/s3eFlurry/lib/android/FlurryAgent.jar', 'c:/marmalade/7.31/extensions/s3eWebView/lib/android/s3eWebView.jar']
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = ['-F$MARMALADE_ROOT/extensions/s3eFacebook/source/iphone/facebook-ios-sdk -framework FacebookSDK -framework SystemConfiguration -framework Security -weak_framework AdSupport -weak_framework Accounts -weak_framework Social -lsqlite3']
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = ['c:/marmalade/7.31/extensions/s3eFacebook/lib/android/libs3eFacebook.so', 'c:/marmalade/7.31/extensions/s3eAmazonInAppPurchasing/lib/android/libs3eAmazonInAppPurchasing.so', 'c:/marmalade/7.31/extensions/s3eAndroidGooglePlayBilling/lib/android/libs3eAndroidGooglePlayBilling.so', 'c:/marmalade/7.31/extensions/s3eAndroidMarketBilling/lib/android/libs3eAndroidMarketBilling.so', 'c:/marmalade/7.31/extensions/s3eSamsungInAppPurchasing/lib/android/libs3eSamsungInAppPurchasing.so', 'c:/marmalade/7.31/extensions/Fortumo/lib/android/libFortumo.so', 'c:/marmalade/7.31/extensions/s3eFlurry/lib/android/libs3eFlurry.so', 'c:/marmalade/7.31/extensions/s3eWebView/lib/android/libs3eWebView.so']
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\notavailable\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.31\quick\target\notavailable\quick_prebuilt.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\tizen\x86\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\tizen\x86\quick_prebuilt.s86',
                 },
         'wp8-arm' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\wp8\arm\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\wp8\arm\quick_prebuilt.s86',
                 },
         'wp8-x86' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\wp8\x86\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\wp8\x86\quick_prebuilt.s86',
                 },
         'ws8-x86' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\ws8\x86\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\ws8\x86\quick_prebuilt.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\android\mips\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.31\quick\target\android\mips\quick_prebuilt.so',
                 },
         'ws81-arm' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\ws81\arm\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\ws81\arm\quick_prebuilt.s86',
                 },
         'ws8-arm' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\ws8\arm\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\ws8\arm\quick_prebuilt.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\arm\quick_prebuilt_d.s3e',
                   'release' : r'c:\marmalade\7.31\quick\target\arm\quick_prebuilt.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\android\mips\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.31\quick\target\android\mips\quick_prebuilt.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\android\x86\quick_prebuilt_d.so',
                   'release' : r'c:\marmalade\7.31\quick\target\android\x86\quick_prebuilt.so',
                 },
         'arm' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\arm\quick_prebuilt_d.s3e',
                   'release' : r'c:\marmalade\7.31\quick\target\arm\quick_prebuilt.s3e',
                 },
         'ws81-x86' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\ws81\x86\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\ws81\x86\quick_prebuilt.s86',
                 },
         'x86' : {
                   'debug'   : r'c:\marmalade\7.31\quick\target\win\quick_prebuilt_d.s86',
                   'release' : r'c:\marmalade\7.31\quick\target\win\quick_prebuilt.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()

######### Configuration: Windows

c = DeployConfig()
config['Windows'] = c
c.os = ['win32']
c.arch = ['x86']
c.target_folder = 'Windows'

######### Configuration: Mac OS X

c = DeployConfig()
config['Mac OS X'] = c
c.os = ['osx']
c.arch = ['x86']
c.target_folder = 'Mac OS X'
